name: Daily Kaggle Trending Downloader

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

# Fixes the Node.js 20 Deprecation warning
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # These will now run on Node 24

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install selenium undetected-chromedriver

      - name: Run Scraper Script
        env:
          KAGGLE_SESSION_ID: ${{ secrets.KAGGLE_SESSION_ID }}
          KAGGLE_XSRF_TOKEN: ${{ secrets.KAGGLE_XSRF_TOKEN }}
        run: python scraper.py

      - name: Upload Downloaded Dataset
        uses: actions/upload-artifact@v4
        with:
          name: kaggle-trending-data
          # Use the relative path from the repo root
          path: downloads/